ERROR - 2023-09-04 20:33:11 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'bdprueba', 3306, '', 0)
#1 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas\Xampp\htdocs\codeigniter4-login\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
#7 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Controllers\Usuarios.php(98): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root2')
#8 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
#9 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Programas\Xampp\htdocs\codeigniter4-login\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas\Xampp\htdocs\codeigniter4-login\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
#6 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Controllers\Usuarios.php(98): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root2')
#7 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
#8 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#9 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Programas\Xampp\htdocs\codeigniter4-login\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-09-04 20:33:11 --> Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Usuarios.php(98): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root2')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-09-04 23:37:18 --> Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 194.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
CRITICAL - 2023-09-04 23:37:36 --> Class "Locale" not found
in SYSTEMPATH\CodeIgniter.php on line 194.
 1 FCPATH\index.php(55): CodeIgniter\CodeIgniter->initialize()
ERROR - 2023-09-04 21:40:22 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'bdprueba' in D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\MySQLi\Connection.php:173
Stack trace:
#0 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\MySQLi\Connection.php(173): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'bdprueba', 3306, '', 0)
#1 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 D:\Programas\Xampp\htdocs\codeigniter4-login\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
#7 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Controllers\Usuarios.php(98): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root2')
#8 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
#9 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#10 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\Programas\Xampp\htdocs\codeigniter4-login\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'bdprueba' in D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\Programas\Xampp\htdocs\codeigniter4-login\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 D:\Programas\Xampp\htdocs\codeigniter4-login\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
#6 D:\Programas\Xampp\htdocs\codeigniter4-login\app\Controllers\Usuarios.php(98): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root2')
#7 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
#8 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
#9 D:\Programas\Xampp\htdocs\codeigniter4-login\system\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\Programas\Xampp\htdocs\codeigniter4-login\public\index.php(67): CodeIgniter\CodeIgniter->run()
#11 {main}
CRITICAL - 2023-09-04 21:40:22 --> Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'bdprueba'
in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuarios`
WHERE `nombre_usuario` = :nombre_usuario:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UsuariosModel.php(15): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\Usuarios.php(98): App\Models\UsuariosModel->obtenerUsuarioPorNombreUsuario('root2')
 7 SYSTEMPATH\CodeIgniter.php(934): App\Controllers\Usuarios->inicioSesion()
 8 SYSTEMPATH\CodeIgniter.php(499): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Usuarios))
 9 SYSTEMPATH\CodeIgniter.php(368): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
